import { Inter } from "next/font/google";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/react";
import Profilecard from "@/app/components/ProfileCard";
import NavBar from "@/app/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div id="container">
              <Profilecard />
              <div id="second-container">
                  <NavBar />
                  <main>
                  <NextUIProvider>
                  {children}
                  </NextUIProvider>
                  </main>
              </div>
          </div>

      </body>
    </html>
  );
}
